CREATE TABLE lecturers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_zip_code VARCHAR(20),
    date_of_birth DATE);


CREATE TABLE lectures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    room_number VARCHAR(20),
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lecturer_id BIGINT,
    CONSTRAINT fk_lecturer
    FOREIGN KEY (lecturer_id)
    REFERENCES lecturers (id));


CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    date_of_birth DATE,
    student_number VARCHAR(20) UNIQUE NOT NULL,
    status VARCHAR(255),
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_zip_code VARCHAR(20),
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE student_lecture (
    student_id BIGINT NOT NULL,
    lecture_id BIGINT NOT NULL,

    PRIMARY KEY (student_id, lecture_id),

    CONSTRAINT fk_student
    FOREIGN KEY (student_id)
    REFERENCES students (id)
    ON DELETE CASCADE,

    CONSTRAINT fk_lecture
    FOREIGN KEY (lecture_id)
    REFERENCES lectures (id)
    ON DELETE CASCADE
);